[tool.poetry]
name = "day12"
version = "0.1.0"
description = ""
authors = ["Anish <anish@codeanish.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
